name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Package
      run: |
        mkdir release
        copy RetainerPriceDrop\bin\x64\Release\RetainerPriceDrop.dll release\
        copy RetainerPriceDrop\RetainerPriceDrop.json release\
        Compress-Archive -Path release\* -DestinationPath RPD.zip
      shell: powershell
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RPD
        path: RPD.zip
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: RPD.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}